export const devMocks = [
  {
    apiName: 'auth.session',
    label: 'Auth / Current session',
    description: '获取当前登录会话，用于判断用户是否已登录以及初始化用户信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'auth.signIn',
    label: 'Auth / Sign in',
    description: '邮箱密码登录接口，用于验证账号并返回会话与用户资料。',
    defaultState: 'normal',
  },
  {
    apiName: 'auth.signUp',
    label: 'Auth / Sign up',
    description: '邮箱注册接口，用于创建新账号并写入基础用户资料。',
    defaultState: 'normal',
  },
  {
    apiName: 'auth.otp',
    label: 'Auth / OTP email',
    description: '发送邮箱验证码或魔法链接，用于免密码登录流程。',
    defaultState: 'normal',
  },
  {
    apiName: 'auth.signOut',
    label: 'Auth / Sign out',
    description: '退出登录接口，用于清理当前会话并回到未登录状态。',
    defaultState: 'normal',
  },
  {
    apiName: 'auth.profile',
    label: 'Auth / Profile upsert',
    description: '新增或更新用户资料，用于保存昵称、头像等个人信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'couple.info',
    label: 'Couple / Info',
    description: '获取情侣关系信息，用于展示双方资料、绑定状态和纪念日基础数据。',
    defaultState: 'normal',
  },
  {
    apiName: 'couple.inviteCode',
    label: 'Couple / Invite code',
    description: '生成情侣绑定邀请码，用于邀请另一半完成账号关联。',
    defaultState: 'normal',
  },
  {
    apiName: 'couple.bind',
    label: 'Couple / Bind',
    description: '使用邀请码绑定情侣关系，用于建立双人空间的数据归属。',
    defaultState: 'normal',
  },
  {
    apiName: 'couple.update',
    label: 'Couple / Update info',
    description: '更新情侣资料，用于修改称呼、恋爱起始日等双人空间信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'couple.timeline',
    label: 'Couple / Timeline',
    description: '获取情侣动态时间线，用于展示日记、照片、AI 创作等共同记录。',
    defaultState: 'normal',
  },
  {
    apiName: 'diary.list',
    label: 'Diary / List',
    description: '获取日记列表，用于首页记录流、搜索结果和历史记录展示。',
    defaultState: 'normal',
  },
  {
    apiName: 'diary.detail',
    label: 'Diary / Detail',
    description: '获取单篇日记详情，用于详情页展示正文、心情、标签和互动信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'diary.create',
    label: 'Diary / Create',
    description: '创建新日记，用于保存编辑器里写下的文字、图片和标签。',
    defaultState: 'normal',
  },
  {
    apiName: 'diary.update',
    label: 'Diary / Update',
    description: '更新已有日记，用于编辑标题、正文、心情、标签等内容。',
    defaultState: 'normal',
  },
  {
    apiName: 'diary.delete',
    label: 'Diary / Delete',
    description: '删除日记记录，用于移除不再需要展示的单篇内容。',
    defaultState: 'normal',
  },
  {
    apiName: 'photo.timeline',
    label: 'Photo / Timeline',
    description: '获取照片时间线，用于按时间展示相册中的照片记录。',
    defaultState: 'normal',
  },
  {
    apiName: 'photo.albumList',
    label: 'Photo / Album list',
    description: '获取相册列表，用于展示不同相册封面、名称和照片数量。',
    defaultState: 'normal',
  },
  {
    apiName: 'photo.albumDetail',
    label: 'Photo / Album detail',
    description: '获取相册详情，用于展示某个相册下的全部照片和基础信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'photo.upload',
    label: 'Photo / Upload',
    description: '上传照片并创建记录，用于保存图片、说明、标签和拍摄时间。',
    defaultState: 'normal',
  },
  {
    apiName: 'photo.delete',
    label: 'Photo / Delete',
    description: '删除照片记录，用于从相册和时间线中移除指定图片。',
    defaultState: 'normal',
  },
  {
    apiName: 'ai.comicJob',
    label: 'AI / Comic job',
    description: '创建 AI 漫画生成任务，用于把文字或照片转成童话漫画。',
    defaultState: 'normal',
  },
  {
    apiName: 'ai.videoJob',
    label: 'AI / Video job',
    description: '创建 AI 短视频生成任务，用于把回忆素材生成纪念视频。',
    defaultState: 'normal',
  },
  {
    apiName: 'ai.jobDetail',
    label: 'AI / Job detail',
    description: '获取 AI 任务详情，用于展示生成进度、结果地址和失败原因。',
    defaultState: 'normal',
  },
  {
    apiName: 'ai.history',
    label: 'AI / Creation history',
    description: '获取 AI 创作历史，用于展示已完成、草稿和生成中的作品。',
    defaultState: 'normal',
  },
  {
    apiName: 'ai.retry',
    label: 'AI / Retry job',
    description: '重试失败的 AI 任务，用于重新进入生成队列并刷新进度。',
    defaultState: 'normal',
  },
  {
    apiName: 'anniversary.list',
    label: 'Anniversary / List',
    description: '获取纪念日列表，用于展示全部重要日期和倒计时信息。',
    defaultState: 'normal',
  },
  {
    apiName: 'anniversary.next',
    label: 'Anniversary / Next',
    description: '获取最近一个纪念日，用于首页或倒计时页突出显示。',
    defaultState: 'normal',
  },
  {
    apiName: 'anniversary.create',
    label: 'Anniversary / Create',
    description: '创建纪念日，用于新增恋爱节点、旅行日或自定义重要日期。',
    defaultState: 'normal',
  },
  {
    apiName: 'anniversary.update',
    label: 'Anniversary / Update',
    description: '更新纪念日，用于修改标题、日期、重复规则和说明。',
    defaultState: 'normal',
  },
  {
    apiName: 'anniversary.delete',
    label: 'Anniversary / Delete',
    description: '删除纪念日，用于移除不再需要提醒或展示的日期。',
    defaultState: 'normal',
  },
  {
    apiName: 'storage.uploadImage',
    label: 'Storage / Upload image',
    description: '上传图片文件到存储桶，用于日记、头像、相册等图片资源。',
    defaultState: 'normal',
  },
  {
    apiName: 'storage.signedUrl',
    label: 'Storage / Signed URL',
    description: '获取临时访问链接，用于预览或下载私有存储中的文件。',
    defaultState: 'normal',
  },
  {
    apiName: 'storage.deleteFile',
    label: 'Storage / Delete file',
    description: '删除存储文件，用于清理已移除记录关联的图片或附件。',
    defaultState: 'normal',
  },
];

export const devPageStates = [
  {
    pageName: 'onboarding',
    label: 'Onboarding',
    defaultState: 'hasData',
  },
  {
    pageName: 'login',
    label: 'Login',
    defaultState: 'hasData',
  },
  {
    pageName: 'home',
    label: 'Home',
    defaultState: 'hasData',
  },
  {
    pageName: 'couple',
    label: 'Couple space',
    defaultState: 'hasData',
  },
  {
    pageName: 'workshop',
    label: 'AI workshop',
    defaultState: 'hasData',
  },
  {
    pageName: 'mine',
    label: 'Mine',
    defaultState: 'hasData',
  },
  {
    pageName: 'diaryEditor',
    label: 'Diary editor',
    defaultState: 'hasData',
  },
  {
    pageName: 'diaryDetail',
    label: 'Diary detail',
    defaultState: 'hasData',
  },
  {
    pageName: 'album',
    label: 'Photo album',
    defaultState: 'hasData',
  },
  {
    pageName: 'photoUpload',
    label: 'Photo upload',
    defaultState: 'hasData',
  },
  {
    pageName: 'comments',
    label: 'Comments',
    defaultState: 'hasData',
  },
  {
    pageName: 'interactionNotifications',
    label: 'Interaction notifications',
    defaultState: 'hasData',
  },
  {
    pageName: 'aiComicConfig',
    label: 'AI comic config',
    defaultState: 'hasData',
  },
  {
    pageName: 'aiVideoConfig',
    label: 'AI video config',
    defaultState: 'hasData',
  },
  {
    pageName: 'aiProgress',
    label: 'AI progress',
    defaultState: 'loading',
  },
  {
    pageName: 'aiHistory',
    label: 'AI history',
    defaultState: 'hasData',
  },
  {
    pageName: 'anniversary',
    label: 'Anniversary',
    defaultState: 'hasData',
  },
  {
    pageName: 'timeCapsule',
    label: 'Time capsule',
    defaultState: 'hasData',
  },
  {
    pageName: 'tags',
    label: 'Tags',
    defaultState: 'hasData',
  },
  {
    pageName: 'search',
    label: 'Search',
    defaultState: 'hasData',
  },
  {
    pageName: 'drafts',
    label: 'Drafts',
    defaultState: 'hasData',
  },
  {
    pageName: 'membership',
    label: 'Membership',
    defaultState: 'hasData',
  },
  {
    pageName: 'settings',
    label: 'Settings',
    defaultState: 'hasData',
  },
  {
    pageName: 'backup',
    label: 'Backup',
    defaultState: 'hasData',
  },
  {
    pageName: 'exportPreview',
    label: 'Export preview',
    defaultState: 'hasData',
  },
  {
    pageName: 'pdfExport',
    label: 'PDF export',
    defaultState: 'hasData',
  },
  {
    pageName: 'emptyState',
    label: 'Empty state',
    defaultState: 'empty',
  },
];
