const completed = 'completed';
const pending = 'pending';

export const devPages = [
  {
    module: '账号与关联',
    design: 'assets/design/引导页.png',
    name: '引导页',
    file: 'app/onboarding.js',
    path: '/onboarding',
    note: '启动引导入口',
    uiStatus: completed,
  },
  {
    module: '账号与关联',
    design: 'assets/design/登录页.png',
    name: '登录页',
    file: 'app/login.js',
    path: '/login',
    note: '登录/授权入口',
    uiStatus: completed,
  },
  {
    module: '账号与关联',
    design: 'assets/design/情侣邀请页.png',
    name: '情侣邀请页',
    file: 'app/account/invite.js',
    path: '/account/invite',
    note: '生成或输入邀请码',
    uiStatus: completed,
  },
  {
    module: '账号与关联',
    design: 'assets/design/情侣绑定确认页.png',
    name: '情侣绑定确认页',
    file: 'app/account/bind-confirm.js',
    path: '/account/bind-confirm',
    note: '确认绑定对象',
    uiStatus: completed,
  },
  {
    module: '账号与关联',
    design: 'assets/design/情侣信息设置页.png',
    name: '情侣信息设置页',
    file: 'app/account/couple-info.js',
    path: '/account/couple-info',
    note: '绑定流程中的主要设置页',
    uiStatus: completed,
  },
  {
    module: '账号与关联',
    design: 'assets/design/情侣信息设置页.png',
    name: '情侣信息设置页 FeaturePage',
    file: 'app/account/couple-settings.js',
    path: '/account/couple-settings',
    note: '同一设计方向的补充页',
    uiStatus: pending,
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/02-首页-记录中心.png',
    name: '首页 / 记录中心',
    file: 'app/(tabs)/index.js',
    path: '/',
    note: '首页 Tab',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/日记编辑器.png',
    name: '日记编辑器',
    file: 'app/diary/editor.js',
    path: '/diary/editor',
    note: '新建/编辑日记',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/日记详情页.png',
    name: '日记详情页',
    file: 'app/diary/detail.js',
    path: '/diary/detail',
    note: '查看日记详情',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/照片上传页.png',
    name: '照片上传页',
    file: 'app/photo/upload.js',
    path: '/photo/upload',
    note: '上传照片记录',
    uiStatus: pending,
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/相册浏览页.png',
    name: '照片相册页',
    file: 'app/photo/album.js',
    path: '/photo/album',
    note: '当前主要相册浏览页',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/相册浏览页.png',
    name: '回忆相册页',
    file: 'app/album/index.js',
    path: '/album',
    note: '另一版相册入口',
    uiStatus: pending,
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/时光胶囊设置页.png',
    name: '时光胶囊设置页',
    file: 'app/time-capsule/settings.js',
    path: '/time-capsule/settings',
    note: '时光胶囊配置',
    uiStatus: pending,
  },
  {
    module: '首页与记录中心',
    design: 'assets/design/标签管理页.png',
    name: '标签管理页',
    file: 'app/tags/index.js',
    path: '/tags',
    note: '标签维护',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/03-情侣空间.png',
    name: '情侣空间',
    file: 'app/(tabs)/couple.js',
    path: '/(tabs)/couple',
    note: '情侣空间 Tab',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/情侣动态详情页.png',
    name: '情侣动态详情页',
    file: 'app/couple/activity-detail.js',
    path: '/couple/activity-detail',
    note: '动态/故事章节详情',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/评论列表页.png',
    name: '评论列表页',
    file: 'app/comments/index.js',
    path: '/comments',
    note: '当前主要评论页',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/评论列表页.png',
    name: '评论列表页互动入口',
    file: 'app/interaction/comments.js',
    path: '/interaction/comments',
    note: '互动模块下的另一版评论页',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/互动通知页.png',
    name: '互动通知页',
    file: 'app/notifications/index.js',
    path: '/notifications',
    note: '当前主要通知页',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/互动通知页.png',
    name: '互动通知兼容入口',
    file: 'app/interaction/notifications.js',
    path: '/interaction/notifications',
    note: '自动重定向到 /notifications',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/04-AI童话工坊.png',
    name: '童话工坊',
    file: 'app/(tabs)/workshop.js',
    path: '/(tabs)/workshop',
    note: 'AI 创作 Tab',
    uiStatus: pending,
    query: { mock: 'true' },
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/AI漫画生成配置页.png',
    name: 'AI 漫画生成配置页',
    file: 'app/ai/comic-config.js',
    path: '/ai/comic-config',
    note: '漫画生成配置',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/文本转漫画页.png',
    name: '文本转漫画页',
    file: 'app/ai/text-to-comic.js',
    path: '/ai/text-to-comic',
    note: '文本生成漫画',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/照片转漫画页.png',
    name: '照片转漫画页',
    file: 'app/ai/photo-to-comic.js',
    path: '/ai/photo-to-comic',
    note: '照片生成漫画',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/AI短视频配置页.png',
    name: 'AI 短视频配置页',
    file: 'app/ai/video-config.js',
    path: '/ai/video-config',
    note: '视频生成配置',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/视频预览编辑页.png',
    name: '视频预览编辑页',
    file: 'app/ai/video-preview.js',
    path: '/ai/video-preview',
    note: '视频结果预览和编辑',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/生成进度页.png',
    name: '生成进度页',
    file: 'app/ai/progress.js',
    path: '/ai/progress',
    note: '当前主要 AI 生成进度页',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/生成进度页.png',
    name: '生成进度兼容页',
    file: 'app/ai/generation-progress.js',
    path: '/ai/generation-progress',
    note: '另一版生成进度入口',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/创作历史展示页.png',
    name: '创作历史展示页',
    file: 'app/ai/history.js',
    path: '/ai/history',
    note: 'AI 历史作品',
    uiStatus: pending,
  },
  {
    module: '纪念日管理',
    design: 'assets/design/06-纪念日管理.png',
    name: '纪念日管理页',
    file: 'app/anniversary/index.js',
    path: '/anniversary',
    note: '纪念日列表和入口',
    uiStatus: pending,
  },
  {
    module: '纪念日管理',
    design: 'assets/design/纪念日添加编辑页.png',
    name: '纪念日添加编辑页',
    file: 'app/anniversary/edit.js',
    path: '/anniversary/edit',
    note: '新增/编辑纪念日',
    uiStatus: pending,
  },
  {
    module: '纪念日管理',
    design: 'assets/design/纪念日倒计时页.png',
    name: '纪念日倒计时页',
    file: 'app/anniversary/countdown.js',
    path: '/anniversary/countdown',
    note: '倒计时展示',
    uiStatus: pending,
  },
  {
    module: '纪念日管理',
    design: 'assets/design/纪念日专属记录模板页.png',
    name: '纪念日专属记录模板页',
    file: 'app/anniversary/template.js',
    path: '/anniversary/template',
    note: '选择纪念日记录模板',
    uiStatus: pending,
  },
  {
    module: '数据与导出',
    design: 'assets/design/PDF导出配置页.png',
    name: 'PDF 导出配置页',
    file: 'app/data/pdf-export.js',
    path: '/data/pdf-export',
    note: '导出范围和样式配置',
    uiStatus: pending,
  },
  {
    module: '数据与导出',
    design: 'assets/design/导出预览页.png',
    name: '导出预览页',
    file: 'app/data/export-preview.js',
    path: '/data/export-preview',
    note: '导出前预览',
    uiStatus: pending,
  },
  {
    module: '数据与导出',
    design: 'assets/design/数据备份恢复页.png',
    name: '数据备份恢复页',
    file: 'app/data/backup.js',
    path: '/data/backup',
    note: '备份/恢复入口',
    uiStatus: pending,
  },
  {
    module: '数据与导出',
    design: 'assets/design/存储空间管理页.png',
    name: '存储空间管理页',
    file: 'app/data/storage.js',
    path: '/data/storage',
    note: '存储占用管理',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/搜索页.png',
    name: '搜索页',
    file: 'app/search.js',
    path: '/search',
    note: '全局搜索',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/草稿箱.png',
    name: '草稿箱',
    file: 'app/drafts.js',
    path: '/drafts',
    note: '草稿管理',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/分享预览页.png',
    name: '分享预览页',
    file: 'app/share-preview.js',
    path: '/share-preview',
    note: '分享卡片预览',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/会员权益说明页.png',
    name: '会员权益说明页',
    file: 'app/membership.js',
    path: '/membership',
    note: '会员权益展示',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/帮助与反馈页.png',
    name: '帮助与反馈页',
    file: 'app/help-feedback.js',
    path: '/help-feedback',
    note: '帮助和反馈入口',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/设置页.png',
    name: '设置页',
    file: 'app/settings.js',
    path: '/settings',
    note: '系统设置',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/空状态页.png',
    name: '空状态页',
    file: 'app/empty-state.js',
    path: '/empty-state',
    note: '空状态示例/演示页',
    uiStatus: pending,
  },
  {
    module: '更多功能',
    design: 'assets/design/08-更多功能.png',
    name: '我的',
    file: 'app/(tabs)/mine.js',
    path: '/(tabs)/mine',
    note: '个人中心入口，复用更多功能总览方向',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/AI漫画生成配置页.png',
    name: 'AI 人设管理',
    file: 'app/ai/character-profile.js',
    path: '/ai/character-profile',
    note: '角色资料设置',
    uiStatus: pending,
  },
  {
    module: 'AI 童话工坊',
    design: 'assets/design/05-AI创作流程.png',
    name: 'AI 漫画结果页',
    file: 'app/ai/comic-result.js',
    path: '/ai/comic-result',
    note: 'AI 生成完成后的漫画结果展示',
    uiStatus: pending,
  },
  {
    module: '情侣空间与互动',
    design: 'assets/design/情侣动态详情页.png',
    name: '情侣故事详情页',
    file: 'app/couple/story-detail.js',
    path: '/couple/story-detail',
    note: '情侣动态详情的故事版详情页',
    uiStatus: pending,
  },
  {
    module: '兼容入口',
    design: 'assets/design/标签管理页.png',
    name: '旧标签入口',
    file: 'app/records/tags.js',
    path: '/records/tags',
    note: '重定向到 /tags',
    uiStatus: pending,
  },
  {
    module: '兼容入口',
    design: 'assets/design/时光胶囊设置页.png',
    name: '旧时光胶囊入口',
    file: 'app/records/time-capsule.js',
    path: '/records/time-capsule',
    note: '重定向到 /time-capsule/settings',
    uiStatus: pending,
  },
];

export const devPageStatusMeta = {
  completed: {
    label: 'UI完成',
    color: '#4F8F68',
    backgroundColor: '#EEF8EF',
  },
  pending: {
    label: '待确认',
    color: '#B08A8F',
    backgroundColor: '#FFF0F2',
  },
};
